<a href="https://colab.research.google.com/github/Luckygsm/internship/blob/master/ML1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
demoData = np.random.randint(10, 100, (10 ,2))
demoData

array([[93, 88],
       [39, 67],
       [24, 32],
       [28, 98],
       [72, 80],
       [48, 33],
       [75, 23],
       [53, 41],
       [81, 24],
       [20, 94]])

In [0]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
demoData=np.random.randint(1,500,(20,4))
demoData

array([[257, 137, 161, 380],
       [ 93, 498,  19, 370],
       [420, 157, 342, 363],
       [322, 345, 112, 155],
       [354, 225, 322, 429],
       [ 47, 244,  55,  90],
       [310,  46,  85, 398],
       [ 22, 163,  82, 387],
       [418, 160, 345, 457],
       [357, 430,  85, 254],
       [225,  77, 290,  70],
       [125, 419,  77, 459],
       [430, 233, 114, 305],
       [312, 265, 352,  89],
       [163, 350, 455, 301],
       [454,  41,  92, 195],
       [455, 210, 228, 324],
       [ 98, 478, 438,  26],
       [481, 315, 279, 154],
       [438, 161, 226, 372]])

In [0]:
scalar_model = MinMaxScaler()
feature_data = scalar_model.fit_transform(demoData)
feature_data

array([[0.51198257, 0.21006565, 0.32568807, 0.81755196],
       [0.1546841 , 1.        , 0.        , 0.79445727],
       [0.8671024 , 0.25382932, 0.74082569, 0.77829099],
       [0.65359477, 0.66520788, 0.21330275, 0.29792148],
       [0.72331155, 0.40262582, 0.69495413, 0.93071594],
       [0.05446623, 0.44420131, 0.08256881, 0.147806  ],
       [0.62745098, 0.01094092, 0.15137615, 0.8591224 ],
       [0.        , 0.26695842, 0.14449541, 0.83371824],
       [0.8627451 , 0.26039387, 0.74770642, 0.99538106],
       [0.72984749, 0.8512035 , 0.15137615, 0.52655889],
       [0.4422658 , 0.07877462, 0.62155963, 0.10161663],
       [0.22440087, 0.82713348, 0.13302752, 1.        ],
       [0.88888889, 0.42013129, 0.21788991, 0.6443418 ],
       [0.63180828, 0.49015317, 0.76376147, 0.14549654],
       [0.30718954, 0.6761488 , 1.        , 0.63510393],
       [0.94117647, 0.        , 0.16743119, 0.39030023],
       [0.94335512, 0.36980306, 0.4793578 , 0.68822171],
       [0.16557734, 0.95623632,

In [0]:
import pandas as pd
df = pd.DataFrame(data=feature_data, columns=['k1', 'k2', 'k3', 'labels'])
df


k1        k2        k3    labels
0   0.511983  0.210066  0.325688  0.817552
1   0.154684  1.000000  0.000000  0.794457
2   0.867102  0.253829  0.740826  0.778291
3   0.653595  0.665208  0.213303  0.297921
4   0.723312  0.402626  0.694954  0.930716
5   0.054466  0.444201  0.082569  0.147806
6   0.627451  0.010941  0.151376  0.859122
7   0.000000  0.266958  0.144495  0.833718
8   0.862745  0.260394  0.747706  0.995381
9   0.729847  0.851204  0.151376  0.526559
10  0.442266  0.078775  0.621560  0.101617
11  0.224401  0.827133  0.133028  1.000000
12  0.888889  0.420131  0.217890  0.644342
13  0.631808  0.490153  0.763761  0.145497
14  0.307190  0.676149  1.000000  0.635104
15  0.941176  0.000000  0.167431  0.390300
16  0.943355  0.369803  0.479358  0.688222
17  0.165577  0.956236  0.961009  0.000000
18  1.000000  0.599562  0.596330  0.295612
19  0.906318  0.262582  0.474771  0.799076

In [0]:
X = df[['k1', 'k2', 'k3']]
y = df['labels']
X

k1        k2        k3
0   0.511983  0.210066  0.325688
1   0.154684  1.000000  0.000000
2   0.867102  0.253829  0.740826
3   0.653595  0.665208  0.213303
4   0.723312  0.402626  0.694954
5   0.054466  0.444201  0.082569
6   0.627451  0.010941  0.151376
7   0.000000  0.266958  0.144495
8   0.862745  0.260394  0.747706
9   0.729847  0.851204  0.151376
10  0.442266  0.078775  0.621560
11  0.224401  0.827133  0.133028
12  0.888889  0.420131  0.217890
13  0.631808  0.490153  0.763761
14  0.307190  0.676149  1.000000
15  0.941176  0.000000  0.167431
16  0.943355  0.369803  0.479358
17  0.165577  0.956236  0.961009
18  1.000000  0.599562  0.596330
19  0.906318  0.262582  0.474771

In [0]:
y

0     0.817552
1     0.794457
2     0.778291
3     0.297921
4     0.930716
5     0.147806
6     0.859122
7     0.833718
8     0.995381
9     0.526559
10    0.101617
11    1.000000
12    0.644342
13    0.145497
14    0.635104
15    0.390300
16    0.688222
17    0.000000
18    0.295612
19    0.799076
Name: labels, dtype: float64

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
X_train.shape

(14, 3)

KNN FOR IRIS EXAMPLE

In [0]:
from sklearn.datasets import load_iris
iris=load_iris()
type(iris)
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [0]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [0]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [0]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [0]:
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [0]:
print(iris.data.shape)

(150, 4)


In [0]:
X=iris.data
y=iris.target

In [0]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=4)
print(X_train.shape)
print(X_test.shape)
       

(120, 4)
(30, 4)


In [0]:
print(y_train.shape)
print(y_test.shape)
       

(120,)
(30,)


In [0]:
from sklearn.neighbors import KNeighborsClasssifier
from sklearn import metrics
k_range=range(1,26)
scores = {}
scores_list = []
for k in k_range:
        knn = KNeighborsClassifier(n_neighbors=k)
        knn.fit(X_train,y_train)
        y_pred=knn.predict(X_test)
        scores[k] = metrics.accuracy_score(y_test,y_pred)
        scores_list.append(metrics.accuracy_score(y_test,y_pred))
scores        


        

ImportError: ignored

In [0]:
        
%matplotlib inline
import matplotlib.pyplot as plt
plt.plot(k_range,scores_list)
plt.xlabel('Value of K for KNN')
plt.ylabel('Testing Accuracy')



NameError: ignored