<a href="https://colab.research.google.com/github/Luckygsm/internship/blob/master/np1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
a=np.arange(12).reshape(2,3,2)
a




array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [3]:
a.shape

(3, 5)

In [11]:
a.ndim

3

In [6]:
a.dtype.name

'int64'

In [12]:
a.itemsize

8

In [13]:
a.size

12

In [14]:
type(a)

numpy.ndarray

In [0]:
b=np.array([6,7,8])

In [16]:
b

array([6, 7, 8])

In [17]:
type(b)

numpy.ndarray

In [19]:
import numpy as np
a=np.array([2,3,4])
a
           

array([2, 3, 4])

In [20]:
a.dtype

dtype('int64')

In [21]:
b=np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [25]:
b=np.array([(1.5,2,3),(4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [26]:
c=np.array([[1,2],[3,4]],dtype=complex)
c
        

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((2,3,5),dtype=np.int16)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [31]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [33]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [34]:
np.arange(0,2,.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])