<a href="https://colab.research.google.com/github/Luckygsm/internship/blob/master/np2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INDEXING,SLICING,ITERATING

In [0]:
import numpy as np
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [0]:
a[2]

8

In [0]:
a[2:5]

array([ 8, 27, 64])

In [0]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [0]:
a[ : :-1] 

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [0]:
 a[:9:3]

array([  0,  27, 216])

In [0]:
for i in a:
  print(i**(1/3.))

0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [0]:
  for row in a:
    print(row)

0
1
8
27
64
125
216
343
512
729


In [0]:
for element in a.flat:
   print(element)

0
1
8
27
64
125
216
343
512
729


N- DIMENSIONAL ARRAYS

In [0]:
d3_array=np.array([[[0,1],
                    [2,3]],
                    [[4,5],
                    [6,7]]])
d3_array

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [0]:
d3_array[:,1,0]

array([2, 6])

In [0]:
d3_array[1]

array([[4, 5],
       [6, 7]])

In [0]:
d3_array[1,1,1:]

array([7])

3DIMENSIONAL

In [0]:
arr=np.array([[[0,1,2],
              [3,4,5],
              [6,7,8]],
              
            [[9,10,11],
            [12,13,14],
            [15,16,17]],
              
            [[18,19,20],
            [21,22,23],
             [24,25,26]]])
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [0]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
arr[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [0]:
arr[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

DOTS

In [0]:
 c = np.array( [[[  0,  1,  2],           
               
                [[100,101,102]]]])
                
c.shape

(1, 2)

In [0]:
c

array([[list([0, 1, 2]), list([[100, 101, 102], [110, 112, 113]])]],
      dtype=object)

In [0]:
c = np.array( [[[  0,  1,  2],            
...                 [ 10, 12, 13]],
...                [[100,101,102],
...                 [110,112,113]]])
c.shape


(2, 2, 3)

In [0]:
c[0,...]  

array([[ 0,  1,  2],
       [10, 12, 13]])

In [0]:
c[...,2] 

array([[  2,  13],
       [102, 113]])

In [0]:
c[...,1]

array([[  1,  12],
       [101, 112]])

In [0]:
for element in a.flat:
  print(element)

0
1
8
27
64
125
216
343
512
729


SHAPE MANIPULATION

In [2]:
import numpy as np
a = np.floor(10*np.random.random((3,4)))
a

array([[7., 2., 7., 8.],
       [8., 4., 7., 3.],
       [0., 2., 2., 7.]])

In [3]:
a.shape

(3, 4)

In [4]:
a.ravel()

array([7., 2., 7., 8., 8., 4., 7., 3., 0., 2., 2., 7.])

In [5]:
a.reshape(6,2) 

array([[7., 2.],
       [7., 8.],
       [8., 4.],
       [7., 3.],
       [0., 2.],
       [2., 7.]])

In [6]:
a.T 

array([[7., 8., 0.],
       [2., 4., 2.],
       [7., 7., 2.],
       [8., 3., 7.]])

In [7]:
a.T.shape

(4, 3)

In [8]:
 a.shape

(3, 4)

In [9]:
 a

array([[7., 2., 7., 8.],
       [8., 4., 7., 3.],
       [0., 2., 2., 7.]])

In [11]:
a.resize((2,6))
a

array([[7., 2., 7., 8., 8., 4.],
       [7., 3., 0., 2., 2., 7.]])

In [12]:
 a.reshape(3,-1)

array([[7., 2., 7., 8.],
       [8., 4., 7., 3.],
       [0., 2., 2., 7.]])

In [14]:
a = np.floor(10*np.random.random((2,2)))
a

array([[1., 8.],
       [9., 0.]])

In [15]:
 b = np.floor(10*np.random.random((2,2)))
>>> b

array([[9., 4.],
       [0., 2.]])

In [16]:
np.vstack((a,b))

array([[1., 8.],
       [9., 0.],
       [9., 4.],
       [0., 2.]])

In [17]:
np.hstack((a,b))

array([[1., 8., 9., 4.],
       [9., 0., 0., 2.]])

In [18]:
from numpy import newaxis
>>> np.column_stack((a,b))  

array([[1., 8., 9., 4.],
       [9., 0., 0., 2.]])

In [19]:
 a = np.array([4.,2.])
>>> b = np.array([3.,8.])
>>> np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [20]:
np.hstack((a,b))  

array([4., 2., 3., 8.])

In [21]:
a[:,newaxis]               

array([[4.],
       [2.]])

In [22]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [25]:
 a = np.floor(10*np.random.random((2,12)))
>>> a


array([[4., 5., 7., 9., 2., 0., 5., 8., 3., 8., 1., 9.],
       [8., 9., 0., 0., 9., 4., 8., 7., 4., 2., 0., 1.]])

In [26]:
 np.hsplit(a,3) 

[array([[4., 5., 7., 9.],
        [8., 9., 0., 0.]]), array([[2., 0., 5., 8.],
        [9., 4., 8., 7.]]), array([[3., 8., 1., 9.],
        [4., 2., 0., 1.]])]

In [27]:
 np.hsplit(a,(3,4))  
  

[array([[4., 5., 7.],
        [8., 9., 0.]]), array([[9.],
        [0.]]), array([[2., 0., 5., 8., 3., 8., 1., 9.],
        [9., 4., 8., 7., 4., 2., 0., 1.]])]

In [28]:
>>> a = np.arange(12)
>>> b = a            # no new object is created
>>> b is a   

True

In [29]:
>>> b.shape = 3,4    # changes the shape of a
>>> a.shape

(3, 4)

In [30]:
>>> c = a.view()
>>> c is a

False

In [31]:
 c.base is a                        
  

True

In [32]:
 c.flags.owndata

False

In [33]:
c.shape = 2,6            
>>> a.shape

(3, 4)