<a href="https://colab.research.google.com/github/Luckygsm/internship/blob/master/np2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INDEXING,SLICING,ITERATING

In [9]:
import numpy as np
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [5]:
a[2]

8

In [17]:
a[2:5]

array([ 8, 27, 64])

In [7]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [8]:
a[ : :-1] 

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [29]:
 a[:9:3]

array([  0,  27, 216])

In [11]:
for i in a:
  print(i**(1/3.))

0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998
