<a href="https://colab.research.google.com/github/Luckygsm/internship/blob/master/np2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INDEXING,SLICING,ITERATING

In [9]:
import numpy as np
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [5]:
a[2]

8

In [17]:
a[2:5]

array([ 8, 27, 64])

In [7]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [8]:
a[ : :-1] 

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [29]:
 a[:9:3]

array([  0,  27, 216])

In [11]:
for i in a:
  print(i**(1/3.))

0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [31]:
  for row in a:
    print(row)

0
1
8
27
64
125
216
343
512
729


In [33]:
for element in a.flat:
   print(element)

0
1
8
27
64
125
216
343
512
729


N- DIMENSIONAL ARRAYS

In [35]:
d3_array=np.array([[[0,1],
                    [2,3]],
                    [[4,5],
                    [6,7]]])
d3_array

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [46]:
d3_array[:,1,0]

array([2, 6])

In [37]:
d3_array[1]

array([[4, 5],
       [6, 7]])

In [38]:
d3_array[1,1,1:]

array([7])

3DIMENSIONAL

In [39]:
arr=np.array([[[0,1,2],
              [3,4,5],
              [6,7,8]],
              
            [[9,10,11],
            [12,13,14],
            [15,16,17]],
              
            [[18,19,20],
            [21,22,23],
             [24,25,26]]])
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [40]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
arr[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [42]:
arr[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

DOTS

In [54]:
 c = np.array( [[[  0,  1,  2],           
               
                [[100,101,102]]]])
                
c.shape

(1, 2)

In [53]:
c

array([[list([0, 1, 2]), list([[100, 101, 102], [110, 112, 113]])]],
      dtype=object)

In [58]:
c = np.array( [[[  0,  1,  2],            
...                 [ 10, 12, 13]],
...                [[100,101,102],
...                 [110,112,113]]])
c.shape


(2, 2, 3)

In [65]:
c[0,...]  

array([[ 0,  1,  2],
       [10, 12, 13]])

In [66]:
c[...,2] 

array([[  2,  13],
       [102, 113]])

In [67]:
c[...,1]

array([[  1,  12],
       [101, 112]])

In [69]:
for element in a.flat:
  print(element)

0
1
8
27
64
125
216
343
512
729


SHAPE MANIPULATION