<a href="https://colab.research.google.com/github/Luckygsm/internship/blob/master/np3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 LINEAR ALGEBRA

In [2]:
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [3]:
 a.transpose()

array([[1., 3.],
       [2., 4.]])

In [4]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [5]:
u = np.eye(2)
u


array([[1., 0.],
       [0., 1.]])

In [0]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

In [8]:
j @ j  

array([[-1.,  0.],
       [ 0., -1.]])

In [9]:
np.trace(u)  

2.0

In [12]:
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [13]:
 np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

PYTHON ARRAY EXAMPLES(DECLARE,APPEND,INDEX,REMOVE,COUNT)

In [14]:
from array import *
my_array=array('i',[1,2,3,4,5])
for i in my_array:
  print(i)

1
2
3
4
5


In [15]:
my_array[1]

2

In [16]:
my_array[2]

3

In [17]:
my_array[0]

1

In [19]:
my_array.append(6)
my_array

array('i', [1, 2, 3, 4, 5, 6, 6])

In [20]:
my_array.insert(0,0)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 6])

In [22]:
my_extnd_array=array('i',[7,8,9,10])
my_array.extend(my_extnd_array)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10])

In [25]:
c=[11,12,13]
my_array.fromlist(c)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10, 11, 12, 13])

In [26]:
my_array.remove(13)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10, 11, 12])

In [27]:
my_array.pop()

12

In [28]:
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10, 11])

In [29]:
my_array.index(5)

5

In [30]:
my_array.reverse()
my_array

array('i', [11, 10, 9, 8, 7, 6, 6, 5, 4, 3, 2, 1, 0])

In [33]:
my_array.buffer_info()


(139847832730240, 13)

In [34]:
my_array.count(11)

1

TO PRINT ONLY EVEN NO AMONG BOTH EVEN N ODD

In [8]:
start=1
end=100
for nume in range(start,end+1):
  if nume % 2 == 0:
    print(nume,end=" ")


2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 100 